import type { User, Listing, Order, Notification, WantedPost } from './types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Brian Kamau',
    email: 'brian.kamau@students.jkuat.ac.ke',
    regNumber: 'ENG-212-0045/2021',
    school: 'School of Engineering',
    yearOfStudy: 3,
    hostel: 'Gate C',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    role: 'seller',
    isVerified: true,
    isTrustedSeller: true,
    totalSales: 47,
    rating: 4.8,
    responseTime: '< 1 hour',
    joinedAt: '2022-03-15',
    badges: ['Trusted Seller', 'Verified Student', 'Fast Responder'],
  },
  {
    id: 'u2',
    name: 'Aisha Wanjiku',
    email: 'aisha.wanjiku@students.jkuat.ac.ke',
    regNumber: 'SCI-312-0092/2022',
    school: 'School of Science',
    yearOfStudy: 2,
    hostel: 'Chiromo',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop',
    role: 'buyer',
    isVerified: true,
    isTrustedSeller: false,
    totalSales: 0,
    rating: 0,
    responseTime: 'N/A',
    joinedAt: '2022-09-01',
    badges: ['Verified Student'],
  },
  {
    id: 'u3',
    name: 'Kevin Ochieng',
    email: 'kevin.ochieng@students.jkuat.ac.ke',
    regNumber: 'BUS-412-0017/2020',
    school: 'School of Business',
    yearOfStudy: 4,
    hostel: 'Gate A',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    role: 'seller',
    isVerified: true,
    isTrustedSeller: true,
    totalSales: 23,
    rating: 4.5,
    responseTime: '< 3 hours',
    joinedAt: '2020-09-10',
    badges: ['Trusted Seller', 'Verified Student'],
  },
];

export const currentUser: User = {
  id: 'me',
  name: 'Grace Muthoni',
  email: 'grace.muthoni@students.jkuat.ac.ke',
  regNumber: 'ICT-312-0101/2022',
  school: 'School of Computing',
  yearOfStudy: 2,
  hostel: 'Gate C',
  avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
  role: 'buyer',
  isVerified: true,
  isTrustedSeller: false,
  totalSales: 3,
  rating: 5.0,
  responseTime: '< 2 hours',
  joinedAt: '2022-09-05',
  badges: ['Verified Student'],
};

export const mockListings: Listing[] = [
  {
    id: 'l1',
    title: 'HP EliteBook 840 G5 — Core i7, 16GB RAM, 512GB SSD',
    price: 52000,
    negotiable: true,
    condition: 'good',
    category: 'laptops',
    subcategory: 'Laptops',
    description: 'Great laptop in good condition. Used for 2 years. Battery holds 4 hours. Minor scratch on lid. Comes with original charger and bag. Perfect for final year project work and coding.',
    images: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&h=450&fit=crop',
    ],
    location: 'Main Library',
    status: 'live',
    seller: mockUsers[0],
    tags: ['laptop', 'hp', 'elitebook', 'core i7', 'student'],
    quantity: 1,
    brand: 'HP',
    defects: 'Minor scratch on lid, keyboard letter W slightly faded',
    ageInMonths: 26,
    reasonForSelling: 'Upgrading to a new laptop for final year project',
    views: 234,
    favourites: 18,
    createdAt: '2024-01-10T08:30:00Z',
    expiresAt: '2024-03-10T08:30:00Z',
    isFavourited: false,
  },
  {
    id: 'l2',
    title: 'Engineering Mathematics 3 by Stroud — 8th Edition',
    price: 850,
    negotiable: false,
    condition: 'good',
    category: 'textbooks',
    subcategory: 'Engineering',
    description: 'Stroud Engineering Mathematics 3rd edition. Some highlighting in first 3 chapters. All pages intact. Great for SMA 2117 students.',
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=450&fit=crop',
    ],
    location: 'Engineering Block',
    status: 'live',
    seller: mockUsers[0],
    tags: ['mathematics', 'stroud', 'engineering', 'SMA 2117', 'textbook'],
    quantity: 1,
    brand: 'Palgrave Macmillan',
    defects: 'Highlighting in first 3 chapters',
    ageInMonths: 18,
    reasonForSelling: 'Done with the unit',
    views: 89,
    favourites: 7,
    createdAt: '2024-01-12T10:00:00Z',
    expiresAt: '2024-03-12T10:00:00Z',
    isFavourited: true,
  },
  {
    id: 'l3',
    title: 'Barely Used Single Mattress — 3.5 by 6 ft',
    price: 2500,
    negotiable: true,
    condition: 'like_new',
    category: 'hostel',
    subcategory: 'Mattresses',
    description: 'Blue foam mattress, used for only one semester. Clean, no stains. Perfect for Gate C or Chiromo hostels. Standard size. Reason: I moved off campus.',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=450&fit=crop',
    ],
    location: 'Gate C Hostel Area',
    status: 'live',
    seller: mockUsers[2],
    tags: ['mattress', 'hostel', 'godoro', 'bed'],
    quantity: 1,
    defects: 'None visible',
    ageInMonths: 6,
    reasonForSelling: 'Moved off campus',
    views: 156,
    favourites: 12,
    createdAt: '2024-01-14T09:00:00Z',
    expiresAt: '2024-03-14T09:00:00Z',
    isFavourited: false,
  },
  {
    id: 'l4',
    title: 'Samsung Galaxy A14 — 128GB, Dual SIM',
    price: 18500,
    negotiable: false,
    condition: 'like_new',
    category: 'electronics',
    subcategory: 'Smartphones',
    description: 'Samsung Galaxy A14 in excellent condition. 6GB RAM, 128GB internal storage. Comes with charger and original box. No cracks, no scratches.',
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600&h=450&fit=crop',
    ],
    location: 'Student Centre',
    status: 'live',
    seller: mockUsers[0],
    tags: ['samsung', 'galaxy', 'phone', 'smartphone', 'android'],
    quantity: 1,
    brand: 'Samsung',
    defects: 'None',
    ageInMonths: 8,
    reasonForSelling: 'Upgraded to another phone',
    views: 312,
    favourites: 24,
    createdAt: '2024-01-15T11:00:00Z',
    expiresAt: '2024-03-15T11:00:00Z',
    isFavourited: false,
  },
  {
    id: 'l5',
    title: 'Jiko (Charcoal Stove) + Sufuria Set',
    price: 800,
    negotiable: true,
    condition: 'good',
    category: 'kitchen',
    subcategory: 'Jikos',
    description: 'Ceramic jiko with 3-piece sufuria set. Works perfectly. Ideal for students cooking in rooms. Handle on one sufuria is loose but functional.',
    images: [
      'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&h=450&fit=crop',
    ],
    location: 'Gate A Hostel Area',
    status: 'live',
    seller: mockUsers[2],
    tags: ['jiko', 'sufuria', 'kitchen', 'cooking', 'hostel'],
    quantity: 1,
    defects: 'Handle on one sufuria is slightly loose',
    ageInMonths: 12,
    reasonForSelling: 'Clearing room before semester ends',
    views: 98,
    favourites: 9,
    createdAt: '2024-01-16T14:00:00Z',
    expiresAt: '2024-03-16T14:00:00Z',
    isFavourited: false,
  },
  {
    id: 'l6',
    title: 'Graphic Design Services — Logos, Posters, CVs',
    price: 500,
    negotiable: true,
    condition: 'brand_new',
    category: 'services',
    subcategory: 'Graphic Design',
    description: 'Professional graphic design services. Logos from KES 500, posters from KES 300, CV design KES 200. Quick turnaround (24–48 hours). Adobe Illustrator and Photoshop.',
    images: [
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=450&fit=crop',
    ],
    location: 'Student Centre',
    status: 'live',
    seller: mockUsers[0],
    tags: ['graphic design', 'logo', 'poster', 'CV', 'design'],
    quantity: 99,
    defects: undefined,
    ageInMonths: 0,
    reasonForSelling: 'Service offering',
    views: 203,
    favourites: 31,
    createdAt: '2024-01-17T09:30:00Z',
    expiresAt: '2024-03-17T09:30:00Z',
    isFavourited: true,
  },
  {
    id: 'l7',
    title: 'Lab Coat — Size M, Used Once',
    price: 600,
    negotiable: false,
    condition: 'like_new',
    category: 'uniforms',
    subcategory: 'Lab Coats',
    description: 'White lab coat size Medium, used only once for one practical session. No stains. Perfect for pharmacy, chemistry or biology students.',
    images: [
      'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600&h=450&fit=crop',
    ],
    location: 'Science Building',
    status: 'live',
    seller: mockUsers[2],
    tags: ['lab coat', 'white coat', 'pharmacy', 'chemistry', 'science'],
    quantity: 1,
    defects: 'None',
    ageInMonths: 3,
    reasonForSelling: 'Changed course',
    views: 67,
    favourites: 5,
    createdAt: '2024-01-18T10:00:00Z',
    expiresAt: '2024-03-18T10:00:00Z',
    isFavourited: false,
  },
  {
    id: 'l8',
    title: 'Casio FX-991EX Scientific Calculator',
    price: 1800,
    negotiable: false,
    condition: 'good',
    category: 'stationery',
    subcategory: 'Calculators',
    description: 'Casio FX-991EX ClassWiz scientific calculator. Works perfectly. Some wear on the case. Great for engineering and science units.',
    images: [
      'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?w=600&h=450&fit=crop',
    ],
    location: 'Engineering Block',
    status: 'live',
    seller: mockUsers[0],
    tags: ['calculator', 'casio', 'scientific', 'engineering', 'maths'],
    quantity: 1,
    brand: 'Casio',
    defects: 'Minor scratches on case',
    ageInMonths: 24,
    reasonForSelling: 'Bought a new one',
    views: 145,
    favourites: 11,
    createdAt: '2024-01-19T08:00:00Z',
    expiresAt: '2024-03-19T08:00:00Z',
    isFavourited: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord1',
    listing: mockListings[0],
    buyer: currentUser,
    seller: mockUsers[0],
    status: 'chat_unlocked',
    amount: 52000,
    platformFee: 2600,
    sellerPayout: 49400,
    commissionRate: 5,
    handoverCode: '384729',
    meetupLocation: 'Main Library',
    meetupTime: '2024-01-25T14:00:00Z',
    mpesaRef: 'QDJ4K8L9MN',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-21T10:30:00Z',
    timeline: [
      { status: 'pending_admin', label: 'Request Sent', time: '2024-01-20T09:00:00Z' },
      { status: 'admin_approved', label: 'Admin Approved', time: '2024-01-20T11:30:00Z' },
      { status: 'paid_escrow', label: 'Payment Received (Escrow)', time: '2024-01-21T08:15:00Z', note: 'KES 52,000 via M-Pesa (Ref: QDJ4K8L9MN)' },
      { status: 'chat_unlocked', label: 'Chat Unlocked — Arrange Meetup', time: '2024-01-21T10:30:00Z' },
    ],
  },
  {
    id: 'ord2',
    listing: mockListings[1],
    buyer: currentUser,
    seller: mockUsers[0],
    status: 'completed',
    amount: 850,
    platformFee: 43,
    sellerPayout: 807,
    commissionRate: 5,
    handoverCode: '192847',
    meetupLocation: 'Engineering Block',
    meetupTime: '2024-01-10T15:00:00Z',
    mpesaRef: 'TYP2X7A3BQ',
    createdAt: '2024-01-08T14:00:00Z',
    updatedAt: '2024-01-10T16:00:00Z',
    timeline: [
      { status: 'pending_admin', label: 'Request Sent', time: '2024-01-08T14:00:00Z' },
      { status: 'admin_approved', label: 'Admin Approved', time: '2024-01-08T15:00:00Z' },
      { status: 'paid_escrow', label: 'Payment in Escrow', time: '2024-01-09T09:00:00Z' },
      { status: 'chat_unlocked', label: 'Chat Unlocked', time: '2024-01-09T09:30:00Z' },
      { status: 'completed', label: 'Order Completed', time: '2024-01-10T16:00:00Z', note: 'Handover code entered. Payment released to seller.' },
    ],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'order',
    title: 'Chat Unlocked! 🎉',
    body: 'Your order for HP EliteBook has been paid. Chat is now open to arrange your meetup.',
    isRead: false,
    createdAt: '2024-01-21T10:30:00Z',
    link: '/orders/ord1',
  },
  {
    id: 'n2',
    type: 'payment',
    title: 'Payment Confirmed ✅',
    body: 'KES 52,000 received in escrow for HP EliteBook order. Ref: QDJ4K8L9MN',
    isRead: false,
    createdAt: '2024-01-21T08:15:00Z',
    link: '/orders/ord1',
  },
  {
    id: 'n3',
    type: 'listing',
    title: 'Price Drop Alert 📉',
    body: 'Engineering Mathematics 3 you favourited dropped in price!',
    isRead: true,
    createdAt: '2024-01-20T14:00:00Z',
    link: '/listings/l2',
  },
  {
    id: 'n4',
    type: 'system',
    title: 'Karibu JKUAT Marketplace! 👋',
    body: 'Your account is verified. Start browsing 200+ campus listings!',
    isRead: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
];

export const mockWantedPosts: WantedPost[] = [
  {
    id: 'w1',
    title: 'Looking for SCO 2101 Data Structures Notes',
    description: 'Need good notes for Data Structures and Algorithms — SCO 2101. CAT summaries especially needed. Willing to pay up to KES 200.',
    maxPrice: 200,
    category: 'textbooks',
    postedBy: currentUser,
    createdAt: '2024-01-19T10:00:00Z',
    offers: 3,
  },
  {
    id: 'w2',
    title: 'Need a Gas Cylinder (6kg) + Regulator',
    description: 'Looking for a 6kg gas cylinder with working regulator. Moving into a bedsitter. Budget KES 2,500.',
    maxPrice: 2500,
    category: 'hostel',
    postedBy: mockUsers[1],
    createdAt: '2024-01-18T15:00:00Z',
    offers: 5,
  },
  {
    id: 'w3',
    title: 'Wanted: Python Programming Textbook',
    description: 'Any edition of "Learning Python" by Mark Lutz or similar Python textbook for ICT students.',
    maxPrice: 800,
    category: 'textbooks',
    postedBy: mockUsers[2],
    createdAt: '2024-01-17T11:00:00Z',
    offers: 2,
  },
];

export const adminStats = {
  pendingListings: 12,
  pendingOrders: 8,
  openDisputes: 3,
  escrowBalance: 287450,
  todayRevenue: 14230,
  weeklyRevenue: 89450,
  monthlyRevenue: 312800,
  totalUsers: 1847,
  newUsersToday: 14,
  activeSellers: 234,
};
